apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ngrw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/quay-or-not-to-quay/nbe-e2e-hjay-tenant/integ-app-gqym/hacbs-test-project-ngrw@sha256:3e897d42061e26d06f4f580e4ac51c4711d4ee3ba00e993f639a3707fa319858
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
